version: "3.9"

services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    network_mode: host
    user: "1001:1001"
    environment:
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /opt/containers/homebridge:/homebridge
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
