version: '3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
     - TZ="America/New_York"
     - VERSION=docker
     - PGID=1000
     - PUID=500
    volumes:
     - /share/homes/containers/plex:/config
     - /share/homes/media:/data
     - /share/homes/media/transcode:/transcode
    devices:
     - /dev/dri:/dev/dri
    privileged: true
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    ports:
     - 10000:8080
     - 10001:9090
    environment:
     - TZ="America/New_York"
     - PGID=1000
     - PUID=500
    volumes:
     - /share/homes/containers/sabnzbd:/config
     - /share/homes/media/downloads/complete:/downloads
     - /share/homes/media/downloads/incomplete:/incomplete-downloads
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 10004:8989
    environment:
      - TZ="America/New_York"
      - PGID=1000
      - PUID=500
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /share/homes/containers/sonarr:/config
      - /share/homes/media/downloads/complete:/downloads
      - /share/homes/media/downloads/incomplete:/incomplete-downloads
      - /share/homes/media/tv:/tv
    links:
      - sabnzbd
      - plex
      - deluge
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    container_name: radarr
    ports:
      - "10002:7878"
    environment:
      - TZ="America/New_York"
      - PGID=1000
      - PUID=500
    volumes:
      - /share/homes/containers/radarr:/config
      - /share/homes/media/downloads/complete:/downloads
      - /share/homes/media/downloads/incomplete:/incomplete-downloads
      - /share/homes/media/downloads/resilio:/downloads-resilio
      - /share/homes/media/movies:/movies
    links:
      - sabnzbd
      - plex
      - deluge
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ="America/New_York"
      - PGID=1000
      - PUID=500
    volumes:
      - /share/homes/containers/deluge:/config
      - /share/homes/media/downloads/deluge:/downloads
  resilio-sync:
    image: resilio/sync
    container_name: resilio
    ports:
      - 55555/tcp
      - 55555/udp
      - "10006:8888"
    volumes:
      - /share/homes/containers/resilio_sync:/mnt/sync
      - /share/homes/media/downloads/resilio:/mnt/mounted_folders/downloads
    restart: always
    user: "500:1000"
    environment:
      - TZ="America/New_York"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ="America/New_York"   
    command: plex sabnzbd sonarr radarr deluge resilio-sync --cleanup --schedule "0 0 4 1/1 * ?"
