version: '2'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
     - TZ="America/New_York"
     - VERSION=docker
     - PGID=100
     - PUID=500
    volumes:
     - /share/Configuration/plex:/config
     - /share/Media:/data
     - /share/Transcode:/transcode
    devices:
     - /dev/dri:/dev/dri
    privileged: true
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    ports:
     - 10000:8080
     - 10001:9090
    environment:
     - TZ="America/New_York"
     - PGID=100
     - PUID=500
    volumes:
     - /share/Configuration/sabnzbd:/config
     - /share/Media/sabnzbd/complete:/downloads
     - /share/Media/sabnzbd/incomplete:/incomplete-downloads
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 10004:8989
    environment:
      - TZ="America/New_York"
      - PGID=100
      - PUID=500
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - /share/Configuration/sonarr:/config
      - /share/Media/sabnzbd/complete:/downloads
      - /share/Media/tv:/tv
    links:
      - sabnzbd
      - plex
      - deluge
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    container_name: radarr
    ports:
      - "10002:7878"
    environment:
      - TZ="America/New_York"
      - PGID=100
      - PUID=500
    volumes:
      - /share/Configuration/radarr:/config
      - /share/Media/sabnzbd/complete:/downloads
      - /share/Media/movies:/movies
    links:
      - sabnzbd
      - plex
      - deluge
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ="America/New_York"
      - PGID=100
      - PUID=500
    volumes:
      - /share/Configuration/deluge:/config
      - /share/Media/sabnzbd/complete:/downloads
  channels-dvr:
    image: fancybits/channels-dvr:latest
    container_name: channels-dvr
    restart: unless-stopped
    network_mode: host
    ports:
      - "8089:8089"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /share/Configuration/channels-dvr:/channels-dvr
      - /share/Media/recordings:/shares/DVR
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 3 * * *" --debug
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ="America/New_York"
      - PGID=100
      - PUID=500
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=1701
    volumes:
      - /share/Configuration/homebridge:/homebridge
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PGID=100
      - PUID=500
      - TZ="America/New_York"
    volumes:
      - /share/Configuration/ddclient:/config
    restart: unless-stopped
networks:
  default:
    ipam:
      config:
        - subnet: 10.0.47.0/24
          gateway: 10.0.47.1
